version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sunflower909
      MYSQL_DATABASE: juristore
      MYSQL_USER: bangnhi
      MYSQL_PASSWORD: sunflower909
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: bangnhi
      WORDPRESS_DB_PASSWORD: sunflower909
      WORDPRESS_DB_NAME: juristore
volumes:
  db_data: {}
